import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription, tap } from 'rxjs';
import { NumberGeneratorService } from './state/number-generator.service';
import * as Model from './state/number-generator.model';
import 'chartjs-adapter-date-fns';
import { enUS } from 'date-fns/locale';
import { ChartDataset } from 'chart.js';

@Component({
  selector: 'app-number-generator',
  templateUrl: './number-generator.component.html',
  styleUrls: ['./number-generator.component.scss']
})
export class NumberGeneratorComponent implements OnInit, OnDestroy {
  generator$: Subscription;
  tableSource$: Subscription;
  dataSource: Model.NumberList;
  cols: any[];
  chartData: any;
  generatedNumber: number | null;
  basicOptions = {
    // scales: {
    //   x: {
    //     type: 'time',
    //     adapters: {
    //       date: {
    //         locale: enUS,
    //       },
    //     },
    //   }
    // }
  };

  constructor(
    private numberGeneratorService: NumberGeneratorService
  ) { }

  ngOnInit(): void {
    this.getList();

    this.cols = [
      { field: 'value', header: 'Number', type: 'number' },
      { field: 'created', header: 'Created Date', type: 'date' },
      { field: 'updated', header: 'Updated Date', type: 'date' },
      { field: 'generator_user', header: 'Generated By', type: 'string' }
    ];
  }

  generateChart() {
    this.chartData = {
      labels: this.dataSource.results.map(val => val['created']),
      datasets: [
        {
          label: 'Random Numbers',
          data: this.dataSource.results.map(val => val['value']),
          fill: true,
          borderColor: '#42A5F5'
        }
      ]
    }

    // this.chartData = [
    //   {
    //     data: this.dataSource.results.map(val => val['value'])
    //   }
    // ]
  }

  getList() {
    this.tableSource$ = this.numberGeneratorService.getRandomNumbersList()
      .pipe(
        tap(res => {
          this.dataSource = res;
          this.generateChart();
        })
      ).subscribe();

  }

  generateNumber() {
    this.generator$ = this.numberGeneratorService.generateRandomNumber()
      .pipe(
        tap(res => {
          if (res) {
            this.generatedNumber = res.value;
            this.getList();
          }
        })
      ).subscribe();
  }

  resetNumber() {
    this.generatedNumber = null;
  }

  ngOnDestroy(): void {
    if (this.generator$) {
      this.generator$.unsubscribe();
    }

    if (this.tableSource$) {
      this.tableSource$.unsubscribe();
    }
  }


}
