import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription, tap } from 'rxjs';
import { NumberGeneratorService } from './state/number-generator.service';
import * as Model from './state/number-generator.model';
import 'chartjs-adapter-date-fns';
import { LazyLoadEvent } from 'primeng/api';

@Component({
  selector: 'app-number-generator',
  templateUrl: './number-generator.component.html',
  styleUrls: ['./number-generator.component.scss']
})
export class NumberGeneratorComponent implements OnInit, OnDestroy {
  generator$: Subscription;
  tableSource$: Subscription;
  dataSource: Model.NumberList;
  tableData: Model.GeneratedNumber[];
  rawSource: Model.GeneratedNumber[];
  cols: any[];
  chartData: any;
  generatedNumber: number | null;
  index = 10;
  totalRecords: number;
  loading: boolean;
  basicOptions = {};

  constructor(
    private numberGeneratorService: NumberGeneratorService
  ) { }

  ngOnInit(): void {
    this.getList();

    this.cols = [
      { field: 'value', header: 'Number', type: 'number' },
      { field: 'created', header: 'Created Date', type: 'date' },
      { field: 'updated', header: 'Updated Date', type: 'date' },
      { field: 'generator_user', header: 'Generated By', type: 'string' }
    ];

    this.numberGeneratorService.getRandomNumbersList(0, 0)
      .pipe(
        tap(res => {
          this.rawSource = res.results;
          this.totalRecords = res.count;
        })
      ).subscribe();
  }

  generateChart() {
    this.chartData = {
      labels: this.dataSource.results.map(val => val['created']),
      datasets: [
        {
          label: 'Random Numbers',
          data: this.dataSource.results.map(val => val['value']),
          fill: true,
          borderColor: '#42A5F5'
        }
      ]
    }

    // this.chartData = [
    //   {
    //     data: this.dataSource.results.map(val => val['value'])
    //   }
    // ]
  }

  nextPage(event: LazyLoadEvent) {
    this.loading = true;
    const { first, rows } = event;

    this.numberGeneratorService.getRandomNumbersList(rows, (first || 0)  + (rows || 0)).pipe(
        tap(res => {
          this.tableData = res.results;
          this.loading = false;
        })
      ).subscribe();
  }

  getList() {
    this.tableSource$ = this.numberGeneratorService.getRandomNumbersList(20, 0)
      .pipe(
        tap(res => {
          this.dataSource = res;
          this.generateChart();
        })
      ).subscribe();

  }

  generateNumber() {
    this.generator$ = this.numberGeneratorService.generateRandomNumber()
      .pipe(
        tap(res => {
          if (res) {
            this.generatedNumber = res.value;
            this.getList();
          }
        })
      ).subscribe();
  }

  resetNumber() {
    this.generatedNumber = null;
  }

  ngOnDestroy(): void {
    if (this.generator$) {
      this.generator$.unsubscribe();
    }

    if (this.tableSource$) {
      this.tableSource$.unsubscribe();
    }
  }


}
